name: my-tests


on:
  push:
    branches: ["main"]
      
jobs:
  test_my_code:
    runs-on   : ubuntu-latest
    steps     :
      - name   : Git-Clone-my-repo
        uses   : actions/checkout@v3
      - run    : |
         cd $GITHUB_WORKSPACE
         python3 -m unittest tests_2.Tests
