name: my-tests
on:
  push:
    branches: ["main"]
      
jobs:
  test_my_code:
    runs-on   : ubuntu-latest
    steps     :
      - run    : |
          pip install tqdm
      - name   : Getting repository
        uses   : actions/checkout@v3
      - run    : |
         cd $GITHUB_WORKSPACE
         python3 -m unittest Tests_2.TestCase
        
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
