name: Try_test_by_your_own
on: 
  workflow_dispatch:
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps     :
      - run    : |
          pip install tqdm
      - name   : Getting repository
        uses   : actions/checkout@v3
      - run    : |
         cd $GITHUB_WORKSPACE
         python3 -m unittest Tests_2.TestCase
      - name   : Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
           ${{ github.actor }} выполнил прогон теста:
           Результат: Success
      - name   : Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
           ${{ github.actor }} выполнил прогон теста:
           Результат: Failure
         
